const appEvents = {
	activateAccount: 'activateAccount',
	resetPassword: 'resetPassword',
	login: 'login',
	logout: 'logout',
	register: 'register',
	updateUser: 'updateUser',
	updateUserProfile: 'updateUserProfile',
	updateUserPassword: 'updateUserPassword',
	updateUserEmail: 'updateUserEmail',
	updateUserAvatar: 'updateUserAvatar',
	updateUserSettings: 'updateUserSettings',
	updateWorkspaceSetings: 'updateWorkspaceSetings',
	updateWorkspace: 'updateWorkspace',
	inviteUserToWorkspace: 'inviteUserToWorkspace',
	removeUserFromWorkspace: 'removeUserFromWorkspace',
	createWorkspace: 'createWorkspace',
	ownerInviteUserToWorkspace: 'ownerInviteUserToWorkspace',
	ownerRemoveUserFromWorkspace: 'ownerRemoveUserFromWorkspace',
	ownerUpdateWorkspace: 'ownerUpdateWorkspace',
	ownerMemberJoinWorkspace: 'ownerMemberJoinWorkspace',
	memberJoinWorkspace: 'memberJoinWorkspace',
	memberLeaveWorkspace: 'memberLeaveWorkspace',
	memberUpdateWorkspace: 'memberUpdateWorkspace',
	memberUpdateWorkspaceSettings: 'memberUpdateWorkspaceSettings',
	memberUpdateWorkspaceAvatar: 'memberUpdateWorkspaceAvatar',
};

export { appEvents };
