swagger: "2.0"
info:
  title: "Ostrich API"
  version: "1.0.0"
  contact:
    name: Orinda Felix
    email: forinda82@gmail.com
    url: https://example.com/
tags:
  - name: Auth
    description: Authentication and authorization
  - name: User
    description: Basic user implementation routes
basePath: /v1
schemes:
  - http
  - https
paths:
  /:
    get:
      responses:
        200:
          description: OK
  /auth/register:
    post:
      tags:
        - Auth
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - password
              - confirmPassword
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
              confirmPassword:
                type: string
            example:
              firstName: Jane
              lastName: Doe
              email: janedoe@gmail.com
              password: pass
              confirmPassword: pass
      responses:
        "200":
          description: OK
  /auth/login:
    post:
      tags:
        - Auth
      parameters:
        - in: body
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        "200":
          description: OK
  /auth/account/password/reset/{userId}/{resetToken}:
    post:
      consumes:
        - application/json
      parameters:
        - in: path
          name: userId
          type: string
          required: true
        - in: path
          type: string
          name: resetToken
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            example:
              password: password
              confirmPassword: password
      responses:
        "200":
          description: OK

  /auth/account/password/reset/link:
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            example:
              email: janedoe@gmail.com
      responses:
        "200":
          description: Ok
