# This is a basic workflow to help you get started with Actions

name: Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - development
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: ostrich-testing-dev-db
        mongodb-port: 27017
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      # NPM install and production script run
    - name: NPM Scripts
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
      
    - name: Set env
      run: npm run env
      
    - name: Build
      run: npm run build

    - name: Deploy to Staging Site
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_SITE_SSH_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.STAGING_SITE_HOST }}
        # Remote user
        REMOTE_USER: ${{ secrets.STAGING_SITE_USERNAME }}
        # Source directory
        SOURCE: ''
        # Target directory
        TARGET: ${{ secrets.REMOTE_TARGET_STAGING_DIGITAL_OCEAN }}
        # Arguments to pass to rsync
        ARGS: "-rltgoDzvO --exclude-from='excludesFile'"
